### PR TITLE
Replace mergehex with srec_cat

### PR DESCRIPTION
**Pull request by stsdc**
`srec_cat` is much easier to install than nrf tools. If this will be applied it will allow to fix CI.

### CODE REVIEW

**Comment by rananna** [comment]
Mergehex allows for compatibility with usb firmware upgrades. New purchasers of nrf52840 board can install full firmware then upgrade wirelessly for future upgrades. Makes it MUCH more complex to do initial firmware if you go back to srec_cat.

**Comment by casainho** [comment]
_New purchasers of nrf52840 board can install full firmware then upgrade wirelessly for future upgrades._
Can you please clarify? I would like to better understand this. Thanks.

**Comment by rananna** [comment]
Srec_cat is not compatible withe the Nordic programmer. Mergehex is compatible. The reason I  keep usb support in the bootloader is to allow a non- developer to easily install the firmware to get started with a newly purchased nrf52840 board. The can simply plug into usb and use the Nordic programmer to load the initial firmware. Once this is done they can update in the future using Bluetooth

**Comment by casainho** [comment]
@rananna , so, that means the user will never need to solder wires to connect the STLinkV2 -- instead, just connect the board to USB on PC and flash our wireless bootloader. This is really important as will easy a lot / reduce the initials barriers to use this project.

So, @stsdc do you have an idea how the Mergehex can be used?

**Comment by stsdc** [comment]
What @rananna  says makes sense. If it is impossible to make with `srec_cat`, then we have to prepare docker with nrf tools installed.

**Comment by charliebruce** [comment]
Can you go into a bit more detail about why `srec_cat` doesn't work but `mergehex` does / give an example of how to reproduce? They should, in theory, produce identical results.

**Comment by driver52** [comment]
I'm not as clued up as you guys but is this the tool you're on about? I think you need to make it compatible with that for the 'lay person'
https://www.nordicsemi.com/Software-and-tools/Development-Tools/nRF-Command-Line-Tools/Download

**Comment by charliebruce** [comment]
I've merged hex files together using `srec_cat` and flashed the resulting file with `nrfjprog` (which is part of the nRF Command Line Tools). There's an example in [this Makefile](https://github.com/charliebruce/nrf5-example-project/blob/master/project.mk#L60) - this approach has been used as part of a couple of different projects I've worked on.

It sounds like the issue may be with the bootloader found on the nRF52840 Dongle - does that bootloader expect an application-only hex file perhaps? I haven't used the USB bootloader before, only the BLE one.

**Comment by charliebruce** [comment]
Did a bit more reading: 

> The example bootloader accepts images that contain a new bootloader, SoftDevice, application, or any combination of these.

So it isn't related to that. 

It's not clear to me why `srec_cat` and `mergehex` would produce different results - they're theoretically doing the exact same operation. 

How are you expecting end users to flash the .hex file - using the "Programmer" tool within nRF Connect?

**Comment by rananna** [comment]
OK, so I can't find the reason for the srec_cat incompatibility on the Nordic website.
The Nordic programmer does choke  using combined files made with srec_cat for some unknown reason, though.
However, upon further reflection, I think I may have created a non-issue.
 I now realise that we only need to merge TWO  firmware hex files to get a new user started. 
The are  the bootloader and the S340 SD hex files.
Since these are unlike to change much, we can merge these using mergehex, and make them available to new users.
All they need to do is to flash this combined hex file using nrfjprog over USB (no srec_cat or mergehex required!) and upon reboot the bootloader will start bluetooth advertising in DFU mode as it cannot find a valid application. 
The new user can then upload the remote control or TSDDZ2 wireless firmware packet using nrfcconnect on bluetooth.
So, it is a non-issue using srec_cat to prepare the merged firmware files.
Sorry to cause a fuss.

**Pull request merged**
