### PR TITLE
enter bootloader with 0x99 ANT_ID - read comments in main.c

### PR DESCRIPTION
**Pull request by rananna**

### CODE REVIEW

**Comment by stsdc** [comment]
I recommend to fix Github actions alongside with breaking changes in the Makefile.
Currently this error spawns: 
`nrfutil settings generate --family NRF52840 --application _build/TSDZ2_wireless.hex --application-version-string 0.5.0 --bootloader-version 1 --bl-settings-version 2 _build/bl_settings.hex `

I do also recommend to remove binary(hex) files from repo.

**Comment by casainho** [comment]
@stsdc , can you please make PRs with needed changes?

There at least hex file for bootloader, that need to exist so the firmware can be built with it...

**Comment by stsdc** [comment]
I'll try to fix this. But it is better be done by author of the PR, because he knows what he changed 😅️

May I ask, where bootloader comes from? Because I can't see any targets in Makefile. Sorry if it's noob question

**Comment by casainho** [comment]
@stsdc bootloader is generated on another repository: https://github.com/OpenSource-EBike-firmware/TSDZ2_wireless-bootloader

**Comment by stsdc** [comment]
We can then create submodule in this repo. `Makefile` will check for hex and if it is not present it will trigger `make` in bootloader submodule.

I know it looks complicated, but it will help us to manage bootloader version used in this project.

**Comment by casainho** [comment]
@stsdc can you submit that PR?

**Comment by stsdc** [comment]
ok, will try.

**Pull request merged**
